require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'buy4earn' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-in-app-review', :path => '../node_modules/react-native-in-app-review'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'buy4earnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'buy4earn-tvOS' do
  # Pods for buy4earn-tvOS

  target 'buy4earn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
